// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { AdminGetAdminsData, AdminGetAdminsResponses, BlogGetBlogsData, BlogGetBlogsResponses, LoginLoginData, LoginLoginErrors, LoginLoginResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class BlogService {
    /**
     * Get Blogs
     */
    public static unnamed<ThrowOnError extends boolean = false>(options?: Options<BlogGetBlogsData, ThrowOnError>) {
        return (options?.client ?? client).get<BlogGetBlogsResponses, unknown, ThrowOnError>({ url: '/api/v1/blogs/', ...options });
    }
}

export class AdminService {
    /**
     * Get Admins
     */
    public static unnamed<ThrowOnError extends boolean = false>(options?: Options<AdminGetAdminsData, ThrowOnError>) {
        return (options?.client ?? client).get<AdminGetAdminsResponses, unknown, ThrowOnError>({ url: '/api/v1/admin/', ...options });
    }
}

export class LoginService {
    /**
     * Login
     */
    public static unnamed<ThrowOnError extends boolean = false>(options: Options<LoginLoginData, ThrowOnError>) {
        return (options.client ?? client).post<LoginLoginResponses, LoginLoginErrors, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            url: '/api/v1/login/access-token',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options.headers
            }
        });
    }
}
