// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AdminCreate
 */
export type AdminCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * AdminPublic
 */
export type AdminPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string | null;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
};

/**
 * Blog
 */
export type Blog = {
    /**
     * Id
     */
    id?: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Updated At
     */
    updated_at?: string;
    /**
     * Admin Id
     */
    admin_id: string;
};

/**
 * Body_login-login
 */
export type BodyLoginLogin = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type BlogGetBlogsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/blogs/';
};

export type BlogGetBlogsResponses = {
    /**
     * Response Blog-Get Blogs
     *
     * Successful Response
     */
    200: Array<Blog>;
};

export type BlogGetBlogsResponse = BlogGetBlogsResponses[keyof BlogGetBlogsResponses];

export type BlogCreateBlogData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Title
         */
        title: string;
        /**
         * Description
         */
        description: string;
    };
    url: '/api/v1/blogs/';
};

export type BlogCreateBlogErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BlogCreateBlogError = BlogCreateBlogErrors[keyof BlogCreateBlogErrors];

export type BlogCreateBlogResponses = {
    /**
     * Successful Response
     */
    201: Blog;
};

export type BlogCreateBlogResponse = BlogCreateBlogResponses[keyof BlogCreateBlogResponses];

export type BlogDeleteBlogData = {
    body?: never;
    path: {
        /**
         * Blog Id
         */
        blog_id: string;
    };
    query?: never;
    url: '/api/v1/blogs/{blog_id}';
};

export type BlogDeleteBlogErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BlogDeleteBlogError = BlogDeleteBlogErrors[keyof BlogDeleteBlogErrors];

export type BlogDeleteBlogResponses = {
    /**
     * Successful Response
     */
    200: Blog;
};

export type BlogDeleteBlogResponse = BlogDeleteBlogResponses[keyof BlogDeleteBlogResponses];

export type BlogGetBlogData = {
    body?: never;
    path: {
        /**
         * Blog Id
         */
        blog_id: string;
    };
    query?: never;
    url: '/api/v1/blogs/{blog_id}';
};

export type BlogGetBlogErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BlogGetBlogError = BlogGetBlogErrors[keyof BlogGetBlogErrors];

export type BlogGetBlogResponses = {
    /**
     * Successful Response
     */
    200: Blog;
};

export type BlogGetBlogResponse = BlogGetBlogResponses[keyof BlogGetBlogResponses];

export type BlogUpdateBlogData = {
    body?: never;
    path: {
        /**
         * Blog Id
         */
        blog_id: string;
    };
    query: {
        /**
         * Title
         */
        title: string;
        /**
         * Description
         */
        description: string;
    };
    url: '/api/v1/blogs/{blog_id}';
};

export type BlogUpdateBlogErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BlogUpdateBlogError = BlogUpdateBlogErrors[keyof BlogUpdateBlogErrors];

export type BlogUpdateBlogResponses = {
    /**
     * Successful Response
     */
    200: Blog;
};

export type BlogUpdateBlogResponse = BlogUpdateBlogResponses[keyof BlogUpdateBlogResponses];

export type AdminGetAdminsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/';
};

export type AdminGetAdminsResponses = {
    /**
     * Response Admin-Get Admins
     *
     * Successful Response
     */
    200: Array<AdminPublic>;
};

export type AdminGetAdminsResponse = AdminGetAdminsResponses[keyof AdminGetAdminsResponses];

export type AdminCreateAdminData = {
    body: AdminCreate;
    path?: never;
    query?: never;
    url: '/api/v1/admin/';
};

export type AdminCreateAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminCreateAdminError = AdminCreateAdminErrors[keyof AdminCreateAdminErrors];

export type AdminCreateAdminResponses = {
    /**
     * Successful Response
     */
    200: AdminPublic;
};

export type AdminCreateAdminResponse = AdminCreateAdminResponses[keyof AdminCreateAdminResponses];

export type LoginLoginData = {
    body: BodyLoginLogin;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLoginError = LoginLoginErrors[keyof LoginLoginErrors];

export type LoginLoginResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginLoginResponse = LoginLoginResponses[keyof LoginLoginResponses];
